# Generated by Django 5.1.4 on 2025-01-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
