# Generated by Django 4.2.20 on 2025-03-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_profile',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='licence_exp_date',
            field=models.DateField(default=False),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='licence_no',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
