# Generated by Django 4.2.20 on 2025-03-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_parent_profile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='licence_exp_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='licence_no',
            field=models.CharField(max_length=20),
        ),
    ]
