# Generated by Django 4.2.20 on 2025-03-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='core.college'),
        ),
        migrations.AlterField(
            model_name='children',
            name='collegetiming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_timing', to='core.collegetiming'),
        ),
    ]
