# Generated by Django 4.2.20 on 2025-03-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_children_college_alter_children_collegetiming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='user',
        ),
    ]
