# Generated by Django 4.2.20 on 2025-03-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_children_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempparent',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
