# Generated by Django 4.2.20 on 2025-03-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tempparent_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempparent',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='parent_pics/'),
        ),
    ]
