# Generated by Django 5.2.3 on 2025-07-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_parent_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofilemapping',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='driverprofilemapping',
            unique_together={('driver', 'college', 'timing')},
        ),
    ]
